### PR TITLE
Milestone 3: New York Time Clone

### PR DESCRIPTION
**Pull request by rajkumardas2701**
## In this project, I've

- created replica of New York Times page using HTML and CSS.
- used CSS properties including Flexbox and Grid to structure the page.

### CODE REVIEW

**Comment by uryelah** [comment]
**Friendly reminder:** You should make sure that your repo looks professional before review.
Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.

Specifically, this pull request is missing a descriptive message.

This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

**Comment by uryelah** [comment]
Hello **Rajkumar Das Das**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all, good job at improving your PR message🎇**

You guys did a really great job with this site, I especially liked the attention to icons and your 'Theory of Inflation' section.

There are still some issues to work through so hang in there 💪 

---------    

### Required changes 🛠 
---------

- [ ] Remember to check if your HTML markup [passes the validator tests](https://validator.w3.org/nu/#textarea). Please fix the existing errors and warnings alike.

- [ ] The navbar logo should be a link.

- [ ] Your nav bar logo image is distorted compare how it looks [in the original site.](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)
Screenshot_2020-03-16 Space Ripples Reveal Big Bang’s Smoking Gun - The New York Times

- [ ] You don't need to add the ad sections. Please remove them.
Note: [OPTIONAL] I find that using ad blockers like **uBlock Origin** really helps when cloning sites and improves your overall online experience. Consider installing that in your browser.
Screenshot_2020-03-16 Space Ripples Reveal Big Bang’s Smoking Gun - The New York Times(1)

- [ ] You are midding the fixed 'footer' present in the original site. Please remember to add it to your clone:

Screenshot_2020-03-16 Space Ripples Reveal Big Bang’s Smoking Gun

- [ ] The `<p>` tags at the footer should actually be links, `<a>` tags.
Check how they are clickable at the[ original site.](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)

- [ ] Same issue as above for the 'Editor Picks', 'More in Space and Astronomy' and 'Most Popular' bottom sections. Both the text and images for them should be wrapped in links.

- [x] The 'Editor Picks' article should be inside an `<aside>` tag. Please add that to your clone.

-----

## OPTIONAL IMPROVEMENTS

- [ ] [OPTIONAL] You already have the class .'pageFooter' so why not making the element a `<footer>` for more semantic HTML?
----

**Kindly fix the REQUIRED above issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by rajkumardas2701** [comment]
Worked and pushed all the suggested changes.
Warning in the html5 validator is about adding <h> tag which I'm trying to avoid to remove bold characters in article tag

**Comment by lekegitrepo** [comment]
### Well done 👏 👏 
### You have implemented the required changes and the page look better now.
### This project is approved.

**_However, try to improve the navbar i.e. make it look better like the original_**

### Reviewed by: Temitayo Adeleke

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — APPROVED** [review]
### Status: Approved

**Pull request merged**
